#!/bin/sh

# This is an example git post-update hook to trigger builders.

# Assumes that daemon part of the fragile is located in parent directory of the
# repository.

for ref; do
    php ../new.php "${ref#*/*/}" "$(git rev-parse --short $ref)"
done
