#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $(basename $0) web-path daemon-path"
    exit 1
fi

web_path="$1"
daemon_path="$2"

set -e

mkdir -p "$web_path" "$daemon_path"

cp .htaccess \
   badge.php build.php config.php dashboard.php footer.php header.php \
   style.css favicon.png \
   "$web_path"
cp -r classes/ vcs/ "$web_path"

cp config.php daemon.php new.php "$daemon_path"
cp -r classes/ vcs/ "$daemon_path"

mkdir -p "$daemon_path/builders"
